import Section from "../components/Section";
import TypeContentCenterLayout4 from "../components/TypeContentCenterLayout4";
import TypeContentCenterLayout1 from "../components/TypeContentCenterLayout1";
import TypeLogosLayoutOnlyThis from "../components/TypeLogosLayoutOnlyThis";
import TypeContentCenterLayout6 from "../components/TypeContentCenterLayout6";
import TypeTestimonialsLayout1M from "../components/TypeTestimonialsLayout1M";
import TypeBlogsLayoutOnlyThis from "../components/TypeBlogsLayoutOnlyThis";
import TypeTeamLayoutOnlyThisM from "../components/TypeTeamLayoutOnlyThisM";
import TypePricingLayoutOnlyThis from "../components/TypePricingLayoutOnlyThis";
import TypeFAQsLayoutOnlyThisM from "../components/TypeFAQsLayoutOnlyThisM";
import TypeContentCenterLayout2 from "../components/TypeContentCenterLayout2";
import DesktopLLogoLeftSubs from "../components/DesktopLLogoLeftSubs";
import DesktopHorizontalLogoLe from "../components/DesktopHorizontalLogoLe";
import "./LandingPage1.css";
const LandingPage1 = () => {
  return (
    <div className="landing-page-1">
      <Section />
      <TypeContentCenterLayout4
        caption="The tools you need"
        loremIpsumDolorSitAmetCon="Rhoncus morbi et augue nec, in id ullamcorper at sit. Condimentum sit nunc in eros scelerisque sed. Commodo in viverra nunc, ullamcorper ut. Non, amet, aliquet scelerisque nullam sagittis, pulvinar. Fermentum scelerisque sit consectetur hac mi. Mollis leo eleifend ultricies purus iaculis."
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--luggage.svg"
        paragraph2="Id eros pellentesque facilisi id mollis faucibus commodo enim."
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--activity.svg"
        paragraph3="Nunc, pellentesque velit malesuada non massa arcu."
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--car.svg"
        paragraph4="Imperdiet purus pellentesque sit mi nibh sit integer faucibus."
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus.svg"
        iconJamIconsOutlineLogos4="/icon--jamicons--outline--logos--arrowright1.svg"
        showLoremIpsumDolor={false}
        paragraph1
        showIconJamIconsOutlineL={false}
        typeContentCenterLayout4Position="unset"
        typeContentCenterLayout4ZIndex="1"
        loremIpsumDolorMarginBlockStart="unset"
        loremIpsumDolorMarginBlockEnd="unset"
        loremIpsumDolorAlignSelf="stretch"
        loremIpsumDolorPosition="relative"
        loremIpsumDolorFontSize="18px"
        loremIpsumDolorLineHeight="140%"
        loremIpsumDolorFontFamily="Roboto"
        loremIpsumDolorColor="#21272a"
        loremIpsumDolorTextAlign="center"
        bibendumAmetAtMargin="unset"
        bibendumAmetAtFlex="1"
        bibendumAmetAtDisplay="flex"
        bibendumAmetAtFlexDirection="column"
        bibendumAmetAtPadding="0px var(--padding-base)"
        bibendumAmetAtBoxSizing="border-box"
        bibendumAmetAtAlignItems="center"
        bibendumAmetAtJustifyContent="flex-start"
        bibendumAmetAtGap="16px"
        paragraphAlignSelf="unset"
        paragraphFontSize="unset"
        paragraphLineHeight="unset"
        paragraphFontFamily="unset"
        paragraphColor="unset"
        paragraphTextAlign="unset"
        paragraphWidth="48px"
        paragraphHeight="48px"
        paragraphOverflow="hidden"
        paragraphFlexShrink="0"
        frameDivDisplay="inline-block"
        frameDivFlexDirection="unset"
        frameDivAlignItems="unset"
        frameDivJustifyContent="unset"
        frameDivGap="unset"
        frameDivPosition="relative"
        frameDivFontSize="18px"
        frameDivLineHeight="140%"
        frameDivFontFamily="Roboto"
        frameDivColor="#21272a"
        frameDivTextAlign="center"
        frameDivFlex="unset"
        frameDivFlexDirection1="row"
        frameDivPadding="0px 16px"
        frameDivJustifyContent1="center"
        frameDivGap1="unset"
        frameDivBackgroundColor="#0f62fe"
        frameDivBorder="2px solid var(--primary-60)"
        frameDivHeight="56px"
        iconJamIconsOutlineLWidth="24px"
        iconJamIconsOutlineLHeight="24px"
        paragraphAlignSelf1="unset"
        paragraphPosition="unset"
        paragraphFontSize1="unset"
        paragraphLineHeight1="unset"
        paragraphFontFamily1="unset"
        paragraphColor1="unset"
        paragraphTextAlign1="unset"
        paragraphDisplay="flex"
        paragraphFlexDirection="row"
        paragraphPadding="0px var(--padding-base)"
        paragraphBoxSizing="border-box"
        paragraphAlignItems="center"
        paragraphJustifyContent="center"
        buttonBackgroundColor="unset"
        buttonBorder="unset"
        buttonBoxSizing="unset"
        buttonHeight="unset"
        buttonDisplay="inline-block"
        buttonFlexDirection="unset"
        buttonPadding="unset"
        buttonAlignItems="unset"
        buttonJustifyContent="unset"
        buttonPosition="relative"
        buttonFontSize="20px"
        buttonLetterSpacing="0.5px"
        buttonLineHeight="100%"
        buttonFontWeight="500"
        buttonFontFamily="Roboto"
        buttonColor="#fff"
        buttonTextAlign="left"
      />
      <TypeContentCenterLayout1
        caption="You Are in GooD Company"
        loremIpsumDolorSitAmetCon="Rhoncus morbi et augue nec, in id ullamcorper at sit. Condimentum sit nunc in eros scelerisque sed. Commodo in viverra nunc, ullamcorper ut. Non, amet, aliquet scelerisque nullam sagittis, pulvinar. Fermentum scelerisque sit consectetur hac mi. Mollis leo eleifend ultricies purus iaculis."
        typeContentCenterLayout1Position="unset"
        typeContentCenterLayout1BackgroundColor="#f2f4f8"
        typeContentCenterLayout1Padding="var(--padding-61xl) var(--padding-61xl) 0px"
        typeContentCenterLayout1ZIndex="2"
        loremIpsumDolorMarginBlockStart="unset"
        loremIpsumDolorMarginBlockEnd="unset"
        loremIpsumDolorAlignSelf="stretch"
        loremIpsumDolorPosition="relative"
        loremIpsumDolorFontSize="18px"
        loremIpsumDolorLineHeight="140%"
        loremIpsumDolorFontFamily="Roboto"
        loremIpsumDolorColor="#21272a"
        loremIpsumDolorTextAlign="center"
        loremIpsumDolorDisplay="inline-block"
      />
      <TypeLogosLayoutOnlyThis
        vector="/vector2.svg"
        group45="/group-45.svg"
        group46="/group-46.svg"
        group47="/group-47.svg"
        vector1="/vector4.svg"
        typeLogosLayoutOnlyThisPosition="unset"
        typeLogosLayoutOnlyThisZIndex="3"
      />
      <TypeContentCenterLayout6
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--luggage1.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--car1.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--plus.svg"
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--arrowright1.svg"
        typeContentCenterLayout6Position="unset"
        typeContentCenterLayout6ZIndex="4"
      />
      <TypeContentCenterLayout1
        caption="Testimonials"
        loremIpsumDolorSitAmetCon="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
        showParagraph={false}
        typeContentCenterLayout1Position="unset"
        typeContentCenterLayout1BackgroundColor="#f2f4f8"
        typeContentCenterLayout1Padding="var(--padding-61xl) var(--padding-61xl) 0px"
        typeContentCenterLayout1ZIndex="5"
        loremIpsumDolorMarginBlockStart="0"
        loremIpsumDolorMarginBlockEnd="5px"
        loremIpsumDolorAlignSelf="unset"
        loremIpsumDolorPosition="unset"
        loremIpsumDolorFontSize="unset"
        loremIpsumDolorLineHeight="unset"
        loremIpsumDolorFontFamily="unset"
        loremIpsumDolorColor="unset"
        loremIpsumDolorTextAlign="unset"
        loremIpsumDolorDisplay="unset"
      />
      <TypeTestimonialsLayout1M
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--chevronleft1.svg"
        group46="/group-46.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--chevronright1.svg"
        typeTestimonialsLayout1MPosition="unset"
        typeTestimonialsLayout1MZIndex="6"
      />
      <TypeBlogsLayoutOnlyThis
        caption="From Our Blog"
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--pictures.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--plus2.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--arrowright2.svg"
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus3.svg"
        iconJamIconsOutlineLogos4="/icon--jamicons--outline--logos--arrowright3.svg"
        iconJamIconsOutlineLogos5="/icon--jamicons--outline--logos--pictures.svg"
        iconJamIconsOutlineLogos6="/icon--jamicons--outline--logos--plus2.svg"
        iconJamIconsOutlineLogos7="/icon--jamicons--outline--logos--arrowright2.svg"
        iconJamIconsOutlineLogos8="/icon--jamicons--outline--logos--plus3.svg"
        iconJamIconsOutlineLogos9="/icon--jamicons--outline--logos--arrowright3.svg"
        iconJamIconsOutlineLogos10="/icon--jamicons--outline--logos--pictures.svg"
        iconJamIconsOutlineLogos11="/icon--jamicons--outline--logos--plus2.svg"
        iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--arrowright2.svg"
        iconJamIconsOutlineLogos13="/icon--jamicons--outline--logos--plus3.svg"
        iconJamIconsOutlineLogos14="/icon--jamicons--outline--logos--arrowright3.svg"
        iconJamIconsOutlineLogos15="/icon--jamicons--outline--logos--pictures.svg"
        iconJamIconsOutlineLogos16="/icon--jamicons--outline--logos--plus2.svg"
        iconJamIconsOutlineLogos17="/icon--jamicons--outline--logos--arrowright2.svg"
        iconJamIconsOutlineLogos18="/icon--jamicons--outline--logos--plus3.svg"
        iconJamIconsOutlineLogos19="/icon--jamicons--outline--logos--arrowright3.svg"
        iconJamIconsOutlineLogos20="/icon--jamicons--outline--logos--plus2.svg"
        iconJamIconsOutlineLogos21="/icon--jamicons--outline--logos--arrowright2.svg"
        typeBlogsLayoutOnlyThisPosition="unset"
        typeBlogsLayoutOnlyThisZIndex="7"
      />
      <TypeTeamLayoutOnlyThisM
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--linkedin.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--twitter.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--instagram.svg"
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--facebook.svg"
        iconJamIconsOutlineLogos4="/icon--jamicons--outline--logos--plus4.svg"
        iconJamIconsOutlineLogos5="/icon--jamicons--outline--logos--arrowright4.svg"
        iconJamIconsOutlineLogos6="/icon--jamicons--outline--logos--linkedin.svg"
        iconJamIconsOutlineLogos7="/icon--jamicons--outline--logos--twitter.svg"
        iconJamIconsOutlineLogos8="/icon--jamicons--outline--logos--instagram1.svg"
        iconJamIconsOutlineLogos9="/icon--jamicons--outline--logos--facebook.svg"
        iconJamIconsOutlineLogos10="/icon--jamicons--outline--logos--plus3.svg"
        iconJamIconsOutlineLogos11="/icon--jamicons--outline--logos--arrowright5.svg"
        iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--linkedin.svg"
        iconJamIconsOutlineLogos13="/icon--jamicons--outline--logos--twitter.svg"
        iconJamIconsOutlineLogos14="/icon--jamicons--outline--logos--instagram1.svg"
        iconJamIconsOutlineLogos15="/icon--jamicons--outline--logos--facebook.svg"
        iconJamIconsOutlineLogos16="/icon--jamicons--outline--logos--plus4.svg"
        iconJamIconsOutlineLogos17="/icon--jamicons--outline--logos--arrowright4.svg"
        iconJamIconsOutlineLogos18="/icon--jamicons--outline--logos--linkedin.svg"
        iconJamIconsOutlineLogos19="/icon--jamicons--outline--logos--twitter.svg"
        iconJamIconsOutlineLogos20="/icon--jamicons--outline--logos--instagram1.svg"
        iconJamIconsOutlineLogos21="/icon--jamicons--outline--logos--facebook.svg"
        iconJamIconsOutlineLogos22="/icon--jamicons--outline--logos--plus3.svg"
        iconJamIconsOutlineLogos23="/icon--jamicons--outline--logos--arrowright5.svg"
        typeTeamLayoutOnlyThisMPosition="unset"
        typeTeamLayoutOnlyThisMBackgroundColor="#f2f4f8"
        typeTeamLayoutOnlyThisMZIndex="8"
      />
      <TypePricingLayoutOnlyThis
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--plus5.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--arrowright6.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--check.svg"
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--check.svg"
        iconJamIconsOutlineLogos4="/icon--jamicons--outline--logos--check.svg"
        iconJamIconsOutlineLogos5="/icon--jamicons--outline--logos--check.svg"
        iconJamIconsOutlineLogos6="/icon--jamicons--outline--logos--check.svg"
        iconJamIconsOutlineLogos7="/icon--jamicons--outline--logos--check1.svg"
        iconJamIconsOutlineLogos8="/icon--jamicons--outline--logos--check2.svg"
        iconJamIconsOutlineLogos9="/icon--jamicons--outline--logos--check1.svg"
        iconJamIconsOutlineLogos10="/icon--jamicons--outline--logos--check1.svg"
        iconJamIconsOutlineLogos11="/icon--jamicons--outline--logos--check1.svg"
        iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--check1.svg"
        iconJamIconsOutlineLogos13="/icon--jamicons--outline--logos--check1.svg"
        iconJamIconsOutlineLogos14="/icon--jamicons--outline--logos--plus6.svg"
        iconJamIconsOutlineLogos15="/icon--jamicons--outline--logos--arrowright7.svg"
        iconJamIconsOutlineLogos16="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos17="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos18="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos19="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos20="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos21="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos22="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos23="/icon--jamicons--outline--logos--check3.svg"
        iconJamIconsOutlineLogos24="/icon--jamicons--outline--logos--check4.svg"
        iconJamIconsOutlineLogos25="/icon--jamicons--outline--logos--check4.svg"
        iconJamIconsOutlineLogos26="/icon--jamicons--outline--logos--check4.svg"
        iconJamIconsOutlineLogos27="/icon--jamicons--outline--logos--check4.svg"
        iconJamIconsOutlineLogos28="/icon--jamicons--outline--logos--plus7.svg"
        iconJamIconsOutlineLogos29="/icon--jamicons--outline--logos--arrowright8.svg"
        iconJamIconsOutlineLogos30="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos31="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos32="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos33="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos34="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos35="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos36="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos37="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos38="/icon--jamicons--outline--logos--check5.svg"
        iconJamIconsOutlineLogos39="/icon--jamicons--outline--logos--check6.svg"
        iconJamIconsOutlineLogos40="/icon--jamicons--outline--logos--check6.svg"
        iconJamIconsOutlineLogos41="/icon--jamicons--outline--logos--check6.svg"
        typePricingLayoutOnlyThisPosition="unset"
        typePricingLayoutOnlyThisZIndex="9"
      />
      <TypeFAQsLayoutOnlyThisM
        caption="Frequently Asked questions"
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--plus8.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--plus8.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--plus8.svg"
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--plus8.svg"
        iconJamIconsOutlineLogos4="/icon--jamicons--outline--logos--plus8.svg"
        typeFAQsLayoutOnlyThisMPosition="unset"
        typeFAQsLayoutOnlyThisMWidth="1px"
        typeFAQsLayoutOnlyThisMZIndex="10"
      />
      <TypeContentCenterLayout2
        loremIpsumDolorSitAmetCon="Rhoncus morbi et augue nec, in id ullamcorper at sit. Condimentum sit nunc in eros scelerisque sed. Commodo in viverra nunc, ullamcorper ut. Non, amet, aliquet scelerisque nullam sagittis, pulvinar. Fermentum scelerisque sit consectetur hac mi. Mollis leo eleifend ultricies purus iaculis."
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--arrowright2.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--arrowright3.svg"
        showCaption={false}
        showButtonText={false}
        iconJamIconsOutlineL
        typeContentCenterLayout2Position="unset"
        typeContentCenterLayout2ZIndex="11"
        loremIpsumDolorMarginBlockStart="unset"
        loremIpsumDolorMarginBlockEnd="unset"
        loremIpsumDolorAlignSelf="stretch"
        loremIpsumDolorPosition="relative"
        loremIpsumDolorFontSize="18px"
        loremIpsumDolorLineHeight="140%"
        loremIpsumDolorFontFamily="Roboto"
        loremIpsumDolorColor="#21272a"
        loremIpsumDolorTextAlign="center"
        loremIpsumDolorDisplay="inline-block"
        bibendumAmetAtMargin="unset"
        bibendumAmetAtBackgroundColor="#0f62fe"
        bibendumAmetAtBorder="2px solid var(--primary-60)"
        bibendumAmetAtBoxSizing="border-box"
        bibendumAmetAtHeight="56px"
        bibendumAmetAtDisplay="flex"
        bibendumAmetAtFlexDirection="row"
        bibendumAmetAtPadding="0px 16px"
        bibendumAmetAtAlignItems="center"
        bibendumAmetAtJustifyContent="center"
        paragraphAlignSelf="unset"
        paragraphFontSize="unset"
        paragraphLineHeight="unset"
        paragraphFontFamily="unset"
        paragraphColor="unset"
        paragraphTextAlign="unset"
        paragraphWidth="24px"
        paragraphHeight="24px"
        paragraphOverflow="hidden"
        paragraphFlexShrink="0"
        buttonsGroupGap="unset"
        buttonsGroupPadding="0px var(--padding-base)"
        buttonsGroupBoxSizing="border-box"
        buttonBackgroundColor="unset"
        buttonBorder="unset"
        buttonBoxSizing="unset"
        buttonHeight="unset"
        buttonDisplay="inline-block"
        buttonFlexDirection="unset"
        buttonPadding="unset"
        buttonAlignItems="unset"
        buttonJustifyContent="unset"
        buttonPosition="relative"
        buttonFontSize="20px"
        buttonLetterSpacing="0.5px"
        buttonLineHeight="100%"
        buttonFontWeight="500"
        buttonFontFamily="Roboto"
        buttonColor="#fff"
        buttonTextAlign="left"
        textContainerPadding="0px 16px"
        textContainerBorder="2px solid var(--primary-60)"
        textContainerHeight="56px"
        buttonTextFontSize="unset"
        buttonTextLetterSpacing="unset"
        buttonTextLineHeight="unset"
        buttonTextFontWeight="unset"
        buttonTextFontFamily="unset"
        buttonTextColor="unset"
        buttonTextTextAlign="unset"
        buttonTextWidth="24px"
        buttonTextHeight="24px"
        buttonTextOverflow="hidden"
        buttonTextFlexShrink="0"
        iconJamIconsOutlineLPosition="unset"
        iconJamIconsOutlineLWidth="unset"
        iconJamIconsOutlineLHeight="unset"
        iconJamIconsOutlineLOverflow="unset"
        iconJamIconsOutlineLFlexShrink="unset"
        iconJamIconsOutlineLFlexDirection="row"
        iconJamIconsOutlineLPadding="0px var(--padding-base)"
        iconJamIconsOutlineLBoxSizing="border-box"
        iconJamIconsOutlineLAlignItems="center"
        iconJamIconsOutlineLJustifyContent="center"
        buttonBorder1="unset"
        buttonBoxSizing1="unset"
        buttonHeight1="unset"
        buttonDisplay1="inline-block"
        buttonFlexDirection1="unset"
        buttonPadding1="unset"
        buttonAlignItems1="unset"
        buttonJustifyContent1="unset"
        buttonPosition1="relative"
        buttonFontSize1="20px"
        buttonLetterSpacing1="0.5px"
        buttonLineHeight1="100%"
        buttonFontWeight1="500"
        buttonFontFamily1="Roboto"
        buttonColor1="#0f62fe"
        buttonTextAlign1="left"
      />
      <DesktopLLogoLeftSubs
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--chevrondown.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--plus2.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--arrowright2.svg"
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos4="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos5="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos6="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos7="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos8="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos9="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos10="/icon--jamicons--outline--logos--chevrondown1.svg"
        button="/button.svg"
        vector="/vector7.svg"
        vector1="/vector8.svg"
        vector2="/vector9.svg"
        vector3="/vector10.svg"
        vector4="/vector11.svg"
        iconJamIconsOutlineLogos11="/icon--jamicons--outline--logos--chevrondown1.svg"
        iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--facebook1.svg"
        iconJamIconsOutlineLogos13="/icon--jamicons--outline--logos--instagram2.svg"
        iconJamIconsOutlineLogos14="/icon--jamicons--outline--logos--chevrondown2.svg"
        iconJamIconsOutlineLogos15="/icon--jamicons--outline--logos--chevrondown2.svg"
        iconJamIconsOutlineLogos16="/icon--jamicons--outline--logos--chevrondown2.svg"
        iconJamIconsOutlineLogos17="/icon--jamicons--outline--logos--chevrondown2.svg"
        iconJamIconsOutlineLogos18="/icon--jamicons--outline--logos--chevrondown2.svg"
        iconJamIconsOutlineLogos19="/icon--jamicons--outline--logos--chevrondown2.svg"
        desktopLLogoLeftSubsPosition="unset"
        desktopLLogoLeftSubsZIndex="12"
      />
      <DesktopHorizontalLogoLe
        iconJamIconsOutlineLogos="/icon--jamicons--outline--logos--home1.svg"
        iconJamIconsOutlineLogos1="/icon--jamicons--outline--logos--chevrondown3.svg"
        iconJamIconsOutlineLogos2="/icon--jamicons--outline--logos--home1.svg"
        iconJamIconsOutlineLogos3="/icon--jamicons--outline--logos--chevrondown3.svg"
        iconJamIconsOutlineLogos4="/icon--jamicons--outline--logos--home1.svg"
        iconJamIconsOutlineLogos5="/icon--jamicons--outline--logos--chevrondown3.svg"
        iconJamIconsOutlineLogos6="/icon--jamicons--outline--logos--home.svg"
        iconJamIconsOutlineLogos7="/icon--jamicons--outline--logos--chevrondown2.svg"
        iconJamIconsOutlineLogos8="/icon--jamicons--outline--logos--home1.svg"
        iconJamIconsOutlineLogos9="/icon--jamicons--outline--logos--chevrondown3.svg"
        iconJamIconsOutlineLogos10="/icon--jamicons--outline--logos--home1.svg"
        iconJamIconsOutlineLogos11="/icon--jamicons--outline--logos--chevrondown3.svg"
        iconJamIconsOutlineLogos12="/icon--jamicons--outline--logos--plus1.svg"
        buttonText="Log In"
        iconJamIconsOutlineLogos13="/icon--jamicons--outline--logos--arrowright.svg"
        iconJamIconsOutlineLogos14="/icon--jamicons--outline--logos--plus.svg"
        buttonText1="Start Free Trial"
        iconJamIconsOutlineLogos15="/icon--jamicons--outline--logos--arrowright1.svg"
        desktopHorizontalLogoLePosition="absolute"
        desktopHorizontalLogoLeMargin="0 !important"
        desktopHorizontalLogoLeTop="0px"
        desktopHorizontalLogoLeLeft="0px"
        desktopHorizontalLogoLeZIndex="13"
      />
    </div>
  );
};

export default LandingPage1;
